import { FieldDefinition } from "@/types/types";
import {
  faCakeCandles,
  faCalendarDays,
  faClock,
  faEnvelope,
  faFlag,
  faHashtag,
  faHourglassEnd,
  faLanguage,
  faLocationDot,
  faMars,
  faPhone,
  faQuestion,
  faSchool,
  faVenus,
  faVenusMars,
} from "@fortawesome/free-solid-svg-icons";

export const profileFields: FieldDefinition[] = [
  { name: "name", label: "Name", type: "text" },
  { name: "profileImage", label: "Profile Image", type: "file" },
  {
    name: "age",
    label: "Age",
    type: "select",
    options: Array.from({ length: 83 }, (_, i) => 18 + i),
    icon: faCakeCandles,
    required: true,
  },
  {
    name: "country",
    label: "Country",
    type: "select",
    options: ["Japan", "Uzbekistan", "USA"],
    icon: faFlag,
    required: true,
  },
  {
    name: "gender",
    label: "Gender",
    type: "radio",
    options: [
      { label: "Male", icon: faMars },
      { label: "Female", icon: faVenus },
      { label: "Other", icon: faQuestion },
    ],
    icon: faVenusMars,
    required: true,
  },
  {
    name: "postalCode",
    label: "Postal Code (7 digits)",
    type: "address",
    keyboardType: "numeric",
    icon: faHashtag,
    required: true,
  },
  {
    name: "prefecture",
    label: "Prefectures",
    type: "address",
    icon: faLocationDot,
    required: true,
  },
  {
    name: "city",
    label: "Municipalities",
    type: "address",
    icon: faLocationDot,
    required: true,
  },
  {
    name: "town",
    label: "Town area",
    type: "address",
    icon: faLocationDot,
    required: true,
  },
  {
    name: "Chome, block number, and number",
    label: "Chome, block number, and number",
    type: "address",
    icon: faLocationDot,
    required: true,
  },
  {
    name: "schoolLocation",
    label: "School Location",
    type: "select",
    options: ["Waseda", "Todai", "Keio"],
    icon: faSchool,
  },
  {
    name: "phoneNumber",
    label: "Phone Number",
    type: "text",
    keyboardType: "phone-pad",
    icon: faPhone,
    required: true,
  },
  {
    name: "emailAddress",
    label: "Email",
    type: "text",
    keyboardType: "email-address",
    icon: faEnvelope,
    required: true,
  },
  {
    name: "JapaneseLevel",
    label: "Japanese Level",
    type: "checkbox",
    options: ["N5", "N4", "N3", "N2", "N1"],
    icon: faLanguage,
  },
  {
    name: "dayWork",
    label: "Working Days",
    type: "checkbox",
    options: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    icon: faCalendarDays,
  },
  {
    name: "hoursWorkFrom",
    label: "Work From",
    type: "text",
    icon: faClock,
    keyboardType: "numeric",
  },
  {
    name: "hoursWorkTo",
    label: "Work To",
    type: "text",
    icon: faHourglassEnd,
    keyboardType: "numeric",
  },
  {
    name: "starred",
    label: "Starred",
    type: "col-checkbox",
    options: [
      "nearStation",
      "beginnerWelcome",
      "salaryIncrease",
      "timeFlexiblity",
      "5/7Workday",
    ],
    icon: faCakeCandles,
  },
];
